profile: dev

modules:
  - quail_modules.data_quality
  - quail_modules.pricing_validation  
  - quail_modules.feature_checks

envs:
  dev:
    orm:
      kind: hybrid  # Use both SQL and MongoDB
      sql:
        url: redshift+psycopg2://awsuser:Pg68h2ZHmVjml@redshift-cluster-2.clxqnyeopl7d.us-east-1.redshift.amazonaws.com:5439/db_quibble
        schema: raw_data
        reflect:
          - { name: pricing_report, schema: raw_data, alias: pricing_report }
          - { name: featurestore, schema: process_data, alias: featurestore }
          - { name: temp_no_bookable, schema: process_data, alias: bookable_data }
          - { name: error_report, schema: process_data, alias: error_report }
        engine_options:
          pool_pre_ping: true
          pool_size: 5
          max_overflow: 10
      mongo:
        url: mongodb://localhost:27017/
        database: quail_quality
        timeout_minutes: 60
  
  prod:
    orm:
      kind: hybrid
      sql:
        url: ${REDSHIFT_PROD_URL}
        schema: raw_data
        reflect:
          - { name: pricing_report, schema: raw_data, alias: pricing_report }
          - { name: featurestore, schema: process_data, alias: featurestore }
          - { name: temp_no_bookable, schema: process_data, alias: bookable_data }
        engine_options:
          pool_pre_ping: true
          pool_size: 10
          max_overflow: 20
      mongo:
        url: ${MONGO_PROD_URL}
        database: quail_quality_prod
        timeout_minutes: 120

params:
  # Data quality parameters
  report_date: ${REPORT_DATE:-2025-09-17}
  min_listing_count: 10
  multiplier_min_rows: 200
  multiplier_z_threshold: 2.5
  multiplier_sample_limit: 25
  
  # Quality thresholds
  min_success_rate: 90.0
  max_error_rate: 5.0
  min_completeness: 0.95
  max_validation_errors: 0
  min_property_quality_score: 0.8
  min_quality_enabled_percent: 0.8

targets:
  daily:
    # Core data quality checks  
    - check_pricing_completeness
    - check_pricing_validity
    - check_feature_completeness
    - check_bookable_availability
    
    # Advanced validations
    - validate_price_consistency
    - validate_listing_references
    - check_data_freshness
    
    # Feature validations
    - validate_feature_distributions
    - validate_feature_schema
    
    # Reporting
    - generate_quality_report
    - save_quality_metrics
  
  weekly:
    - generate_weekly_report
    - analyze_quality_trends
    - cleanup_old_records
    - generate_feature_report
    - generate_pricing_insights

  validation_suite:
    # Comprehensive validation pipeline
    - check_pricing_completeness
    - check_pricing_validity
    - validate_price_consistency
    - validate_pricing_business_rules
    - check_feature_completeness
    - validate_feature_distributions
    - validate_feature_schema

default_target: "daily"